# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.1"

    - uses: leafo/gh-actions-luarocks@v2

    - name: setup 
      run: |
        luarocks install moonscript

    - name: compile
      run: |
        sh compile.sh
